# Generated by Django 2.2.1 on 2019-08-04 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('conf_code', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('meeting_start_time', models.TextField(blank=True, max_length=100, null=True)),
                ('meeting_end_time', models.TextField(blank=True, max_length=100, null=True)),
                ('organizer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('organizer_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('invite_description', models.TextField(blank=True, max_length=150, null=True)),
                ('meeting_title', models.CharField(blank=True, max_length=50, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('twilio_call_id', models.TextField(max_length=100)),
                ('twilio_recording_id', models.TextField(blank=True, max_length=60, null=True)),
                ('meeting_type', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('subject', models.TextField(blank=True, max_length=30, null=True)),
                ('lbc_order_id', models.TextField(blank=True, max_length=60, null=True)),
                ('user', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.TextField(blank=True, max_length=30, null=True)),
                ('participant_email', models.EmailField(blank=True, max_length=80, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.SlugField(max_length=30)),
                ('last_name', models.SlugField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('activation_key', models.SlugField()),
                ('remember_token', models.SlugField()),
                ('access_token', models.SlugField()),
                ('status', models.BooleanField()),
                ('provider', models.CharField(max_length=30)),
                ('provider_token', models.SlugField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_text', models.TextField(blank=True, max_length=30, null=True)),
                ('item_type', models.CharField(blank=True, max_length=80, null=True)),
                ('updated_item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_item_text', models.CharField(blank=True, max_length=100, null=True)),
                ('item_task', models.CharField(blank=True, max_length=80, null=True)),
                ('speaker', models.EmailField(blank=True, max_length=50, null=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting')),
            ],
            options={
                'db_table': 'meeting_items',
            },
        ),
        migrations.CreateModel(
            name='LinkMeetingParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.Participant')),
            ],
            options={
                'db_table': 'link_meeting_participant',
            },
        ),
    ]
