# Generated by Django 2.2.1 on 2019-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='remember_token',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
