# Generated by Django 2.2.1 on 2019-08-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20190804_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingitem',
            name='meeting',
        ),
        migrations.AddField(
            model_name='meetingitem',
            name='meeting_id',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
            preserve_default=False,
        ),
    ]
