# Generated by Django 2.2.1 on 2019-08-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20190804_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingitem',
            old_name='meeting_id',
            new_name='meeting',
        ),
    ]
